"""empty message

Revision ID: 2737bc430538
Revises: 6b64e47f655d
Create Date: 2024-05-12 06:44:50.232066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2737bc430538'
down_revision: Union[str, None] = '6b64e47f655d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_index',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('name', sa.TEXT(), nullable=False, comment='Наименование показателя'),
    sa.Column('limit', sa.INTEGER(), nullable=False, comment='Предельное значение метрики'),
    sa.Column('create_stamp', sa.TIMESTAMP(), nullable=False, comment='Дата создания'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник показателей качества продукта'
    )
    with op.batch_alter_table('parts_quality', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quality_index', ['metric_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('googleDrive', 'yandexDisk', name='storagetype'),
               type_=sa.String(),
               comment='Тип источника',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('googleDrive', 'yandexDisk', name='storagetype'),
               comment=None,
               existing_comment='Тип источника',
               existing_nullable=False)

    with op.batch_alter_table('parts_quality', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('quality_index')
    # ### end Alembic commands ###
