"""empty message

Revision ID: d738d80cda57
Revises: 46f0b8f1ec7a
Create Date: 2024-04-23 01:47:29.318811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd738d80cda57'
down_revision: Union[str, None] = '46f0b8f1ec7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор'),
    sa.Column('create_stamp', sa.TIMESTAMP(), nullable=False, comment='Дата создания'),
    sa.Column('amount', sa.INTEGER(), nullable=False, comment='Сумма'),
    sa.PrimaryKeyConstraint('id'),
    comment='Test table'
    )
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='account_pkey')
    )
    op.drop_table('test')
    # ### end Alembic commands ###
